version: '3.7'

services:
  # MySQL database service
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Java application service
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SERVER_PORT: 8080

volumes:
  mysql_data:
