{
 "title": "Spring HTTP Example",
 "description": "An example dashboard for Spring HTTP metrics",
 "tags": [
  "spring",
  "http"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "_instance_label_name", "query": "instance" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{job=\"$job\",}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS by URI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (irate(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPS by instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (irate(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg Latency (by instance)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_sum{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n / \n(sum by(instance) (increase(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) != 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg Latency (by outcome)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(outcome) (increase(http_server_requests_seconds_sum{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))\n / \n (sum by(outcome) (increase(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) != 0)",
     "legendFormat": "{{outcome}}"
    }
   ]
  }
 ]
}