route:
  receiver: 'telegram'
receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '{{ BOT_TOKEN }}'
        api_url: 'https://api.telegram.org'
        chat_id: '{{ CHAT_ID }}'
        message:  "Alertname: {{ .GroupLabels.alertname }}\n Severity: {{ .CommonLabels.severity }}\n {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        parse_mode: ''